version: '3.6'
services:
  influxdb:
    image: influxdb:1.8
    ports:
      - '8086:8086'
    volumes:
      - influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=seyalthiran
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD={change_while_deploy}
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD={change_while_deploy}
  chronograf:
    image: chronograf
    ports:
      - '8888:8888'
    volumes:
      - chronograf:/var/lib/chronograf
  grafana:
    image: grafana/grafana:7.5.7
    ports:
      - '3001:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ${PWD}/grafana-config/grafana.ini:/etc/grafana/grafana.ini
volumes:
  influxdb: {}
  grafana-storage: {}
  chronograf: {}
